### ISSUE TITLE
Cannot find module 'dicer'

### ISSUE THREAD

**Issue by Liu-Young** [expressjs/multer#110]
I use multer in my project throw error below.
```javascript
module.js:340
    throw err;
          ^
Error: Cannot find module 'dicer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (d:\ProjectSpace\blog\node_modules\multer\node_modules\busboy\lib\types\multipart.js:11:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I new to multer, how to fixe it?

**Comment by LinusU** [comment]
Hmm, it gets installed for me. Could you try and remove your `node_modules` folder and then run `npm install` again?
