### ISSUE TITLE
Express Error on app start

### ISSUE THREAD

**Issue by dsine-de** [expressjs/multer#156]
I got an error with the newest version of multer (1.0.0) and express 4.13.1 on app start:

...\node_modules\express\lib\router\route.js:196
        throw new Error(msg);
              ^
Error: Route.post() requires callback functions but got a [object Object]
   at Route.(anonymous function) [as post] (...\node_modules\express\lib\router\route.js:196:15)
   at EventEmitter.app.(anonymous function) (...\node_modules\express\lib\application.js:481:19)
   at Object.<anonymous> (...\server\app.js:33:5)
   at Module._compile (module.js:460:26)
   at Object.Module._extensions..js (module.js:478:10)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at Object.<anonymous> (...\server\bin\www:14:11)
   at Module._compile (module.js:460:26)
   at Object.Module._extensions..js (module.js:478:10)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Function.Module.runMain (module.js:501:10)
   at startup (node.js:129:16)

Version 0.1.8 of multer worked.

**Comment by dsine-de** [comment]
Oh - syntax changed. It's working now.

**Comment by LinusU** [comment]
Glad you got it working :)

**Comment by nataCarballo** [comment]
How did you solve it?
I´ve got a same problem, I need help, please!

**Comment by valentinbdv** [comment]
A bit late but I got the same error.

multer version : 1.3.1
express version: 4.14.0
