### ISSUE TITLE
TypeError: Cannot read property 'transfer-encoding' of undefined

### ISSUE THREAD

**Issue by gabeio** [expressjs/multer#167]
a new issue for a new issue LOL 

```
/home/travis/build/gabeio/<repo>/node_modules/multer/node_modules/type-is/index.js:93
  return req.headers['transfer-encoding'] !== undefined
                    ^
TypeError: Cannot read property 'transfer-encoding' of undefined
    at hasbody (/home/travis/build/gabeio/<repo>/node_modules/multer/node_modules/type-is/index.js:93:21)
    at typeofrequest (/home/travis/build/gabeio/<repo>/node_modules/multer/node_modules/type-is/index.js:127:8)
    at multerMiddleware (/home/travis/build/gabeio/<repo>/node_modules/multer/lib/make-middleware.js:12:10)
    at Object.<anonymous> (/home/travis/build/gabeio/<repo>/lib/admin.js:9:4371)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/gabeio/<repo>/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/travis/build/gabeio/<repo>/lib/app.js:9:14528)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/gabeio/<repo>/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/travis/build/gabeio/<repo>/test/admin.js:9:7)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/gabeio/<repo>/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at /home/travis/build/gabeio/<repo>/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/gabeio/<repo>/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/home/travis/build/gabeio/<repo>/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/home/travis/build/gabeio/<repo>/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/gabeio/<repo>/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Function.Module.runMain (module.js:487:10)
    at runFn (/home/travis/build/gabeio/<repo>/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /home/travis/build/gabeio/<repo>/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /home/travis/build/gabeio/<repo>/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /home/travis/build/gabeio/<repo>/node_modules/async/lib/async.js:46:16
    at /home/travis/build/gabeio/<repo>/node_modules/async/lib/async.js:351:13
    at /home/travis/build/gabeio/<repo>/node_modules/async/lib/async.js:46:16
    at done (/home/travis/build/gabeio/<repo>/node_modules/async/lib/async.js:236:21)
    at /home/travis/build/gabeio/<repo>/node_modules/async/lib/async.js:37:16
    at /home/travis/build/gabeio/<repo>/node_modules/async/lib/async.js:348:17
    at LOOP (fs.js:1456:14)
    at process._tickCallback (node.js:337:11)
```

hot off travis lol ;]

**Comment by LinusU** [comment]
The middleware did not get called correctly. The problem should be at `/home/travis/build/gabeio/<repo>/lib/admin.js:9:4371` (minified file? no source maps?).

How are you adding/calling the middleware?

**Comment by gabeio** [comment]
oh wow. found the issue! yes I am calling it wrong lol sometimes it helps to look at the compiled source (I use livescript...) I put `.post upload (req,res,next)->` I expected: `.post(upload(),function(req,res,next){` I got `.post(upload(function(req,res,next){` super derp! sorry for all the issue :flushed:

**Comment by gabeio** [comment]
@LinusU yup that fixed it LOL the files aren't minified just compiled to js I don't think minification really does anything for node (unless I am missing some awesomeness lol)

**Comment by LinusU** [comment]
Hehe, no problem :)
