### ISSUE TITLE
TypeError: app.use() requires middleware functions

### ISSUE THREAD

**Issue by abbshr** [expressjs/multer#169]
this is the example code:

```coffee
app.use logger 'dev'
app.use bodyParser.json()
app.use bodyParser.urlencoded()
app.use multer inMemory: yes
```

when it executes, throw an TypeError from `app.use multer: inMemory: yes`:

```
TypeError: app.use() requires middleware functions
    at EventEmitter.use (/Users/ran/github/lbs-app/node_modules/express/lib/application.js:206:11)
    at Object.<anonymous> (/Users/ran/github/lbs-app/app.js:69:7)
    at Object.<anonymous> (/Users/ran/github/lbs-app/app.js:108:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ran/github/lbs-app/bin/www:7:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)
```

I was confused at first, because the same code works well on my laptap, and when I check the dependencies' version, I found multer: `0.1.8 => 1.0.1`...

**Comment by macneib** [comment]
So I'm thinking you had the same problem as me.
I had my multer configuration in my express config file, so now I'm rushing a fix to get it nested in to a route.

for example: in my routes.js file

````javascript
module.exports = function(app) {
<-SNIP->
  app.use('/api/uploads', require('./api/upload'));
<-SNIP->
};
````
and in /api/uploads/index.js

````javascript
'use strict';
var express = require('express');
var controller = require('./upload.controller');

var multer = require('multer');
var os = require('os');
var uuid = require('node-uuid');
var storage = multer.diskStorage({
  destination: function (req, file, cb) { cb(null, os.tmpdir()) },
  filename: function (req, file, cb) { cb(null, uuid.v4());}
});
// Create the multer instance here
var upload = multer({ storage: storage, limits: { fileSize: 10 * 1024 * 1024}});

var router = express.Router();

// File Upload route
router.post('/', upload.single('file'), controller.upload);

module.exports = router;

````

I'm still finishing up my code, but that's a rough idea of what the change is.
Good luck!

**Comment by LinusU** [comment]
@abbshr The syntax for using multer has changed with version `1.0.0`, please see the readme on how to use it now.

You shouldn't have been updated automatically thought as this was a major version bump. If your dependencies contains `"multer": "*"` I strongly urge you to set it to `"multer": "^1.0.1"` instead. Else you will get the same problem with all backwards incompatible changes that we release.

@macneib That looks good! :+1: 

The disk storage defaults the `destination` to `os.tmpdir()` so you could drop that if you want to. It also defaults to generating names with 16 bytes of random data as a hex-string (e.g. `a087fda2cf19f341ddaeacacab285acc`), if this works for you you could drop `node-uuid` and use the storage as this:

```javascript
var storage = multer.diskStorage({})
var limits = { fileSize: 10 * 1024 * 1024 }

var upload = multer({ storage: storage, limits: limits })
```

**Comment by Kushan-** [comment]
my server.js



will you please help me to figure out the issue??









var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var ss_data = require('./routes/uiData.js');
//var users = require('./routes/users');

var app = express();



app.use(logger('dev'));       //will show logs of express
//app.use(bodyParser.json());
//app.use(bodyParser.urlencoded({ extended: false }));
//app.use(cookieParser());




//express midle ware
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', ss_data);    
console.log(__dirname);

//app.use('/users', users);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

const port	= process.env.PORT || 7120;
const hostname	= process.env.NODE_ENV || 'localhost';

app.listen(port, hostname, function(){
  console.log(`Server running at http://${hostname}:${port}/`);
}); 




/home/kush/workspace/old_workspace/JavaScript/stockStimulation/rest-server/node_modules/express/lib/router/index.js:458
      throw new TypeError('Router.use() requires middleware function but got a ' + gettype(fn));
      ^

TypeError: Router.use() requires middleware function but got a Object
    at Function.use (/home/kush/workspace/old_workspace/JavaScript/stockStimulation/rest-server/node_modules/express/lib/router/index.js:458:13)
    at EventEmitter.<anonymous> (/home/kush/workspace/old_workspace/JavaScript/stockStimulation/rest-server/node_modules/express/lib/application.js:219:21)
    at Array.forEach (native)
    at EventEmitter.use (/home/kush/workspace/old_workspace/JavaScript/stockStimulation/rest-server/node_modules/express/lib/application.js:216:7)
    at Object.<anonymous> (/home/kush/workspace/old_workspace/JavaScript/stockStimulation/rest-server/server.js:32:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

**Comment by LinusU** [comment]
That doesn't seem related to multer at all, but I think that the problem is that `ss_data` is an object instead of a function. What's in `routes/uiData.js`?

**Comment by sagarpandav** [comment]
var express = require('express');
var app = express();
var dataFile = require('./data/data.json');
app.set('port', process.env.PORT || 3000);
app.use(require('./routes/index'));
var server = app.listen(app.get('port'), function() {
  console.log('Listening on port '+app.get('port'));
});


error is 
H:\express\node_modules\express\lib\application.js:210
    throw new TypeError('app.use() requires a middleware function')
    ^

TypeError: app.use() requires a middleware function
    at Function.use (H:\express\node_modules\express\lib\application.js:210:11)
    at Object.<anonymous> (H:\express\app\app.js:7:5)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

**Comment by LinusU** [comment]
@sagarpandav Could it be that you have forgot to do `module.exports = ` in your `routes/index.js` file?

**Comment by vishalsrivastavaofficial** [comment]
@LinusU Thanks bro.. you solved my problem...

**Comment by joseescalon96** [comment]
Index.js:
const express = require('express');
const socketio = require('socket.io');
const http = require('http');

const PORT = process.env.PORT || 5000;

const router = require('./router');

const app = express();
const server = http.createServer(app);
const io = socketio(server);

app.use(router);

server.listen(PORT, () => console.log(`Server has started on port ${PORT}`));

Router.js:
const express = require('express');
const router = express.Router();

router.get(`/`, (req, res) => {
    res.send('server is up and running');
});

module.export = router;

This throws an error that I dont know how to fix can someone help me?

throw new TypeError('app.use() requires a middleware function')
    ^

TypeError: app.use() requires a middleware function
    at Function.use (/Users/Andres/Desktop/chat-app-2/server/node_modules/express/lib/application.js:210:11)
    at Object.<anonymous> (/Users/Andres/Desktop/chat-app-2/server/index.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ShahzadAli12345** [comment]
throw new TypeError('app.use() requires a middleware function')
    ^

TypeError: app.use() requires a middleware function
    at Function.use (C:\Users\lenovo\Desktop\Web Final Project Shahzad Ali\node_modules\express\lib\application.js:217:11)
    at Object.<anonymous> (C:\Users\lenovo\Desktop\Web Final Project Shahzad Ali\app.js:16:5)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by AmoghKharche** [comment]
const dotenv = require( "dotenv");
const mongoose = require('mongoose');
const express = require("express");
const app = express();

dotenv.config({path:'./config.env'})

//const User = require('./model/userSchema')


const DB = process.env.DATABASE
mongoose.connect(DB).then(()=>{
    console.log("connected to database succesully")
}).catch((err)=>{
    console.log('connection failed');
});

app.use(require('./router/auth'));

const middleware = (req,res,next)=>{
    console.log("Hello to my MiddleWare");
    next();
}
app.get("/",(req,res)=>{
    res.send("Hello0 about World");
})

app.get('/about', middleware, (req, res)=>{
    console.log("Hello")
    res.send("Hello0 aboutt World");
});


app.listen(3001,()=>{
    console.log("Server is running at 3001")
})




F:\Internship\voiceofvoters\node_modules\express\lib\application.js:217
    throw new TypeError('app.use() requires a middleware function')
    ^

TypeError: app.use() requires a middleware function
    at Function.use (F:\Internship\voiceofvoters\node_modules\express\lib\application.js:217:11)
    at Object.<anonymous> (F:\Internship\voiceofvoters\server\Server.js:18:5)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
[nodemon] app crashed - waiting for file changes before starting...
 
 Help me with this
