### ISSUE TITLE
simple multer issue

### ISSUE THREAD

**Issue by anand-ma** [expressjs/multer#276]
```text
Error: Unexpected field
    at makeError (D:\Anand\Workspace\PM_PORTAL\node_modules\multer\lib\make-error.js:12:13)
    at wrappedFileFilter (D:\Anand\Workspace\PM_PORTAL\node_modules\multer\index.js:39:19)
    at Busboy.<anonymous> (D:\Anand\Workspace\PM_PORTAL\node_modules\multer\lib\make-middleware.js:112:7)
    at Busboy.emit (events.js:118:17)
    at Busboy.emit (D:\Anand\Workspace\PM_PORTAL\node_modules\multer\node_modules\busboy\lib\main.js:31:35)
    at PartStream.<anonymous> (D:\Anand\Workspace\PM_PORTAL\node_modules\multer\node_modules\busboy\lib\types\multipart.js:208:13)
    at PartStream.emit (events.js:107:17)
    at HeaderParser.<anonymous> (D:\Anand\Workspace\PM_PORTAL\node_modules\multer\node_modules\busboy\node_modules\dicer\lib\Dicer.js:51:16)
    at HeaderParser.emit (events.js:107:17)
    at HeaderParser._finish (D:\Anand\Workspace\PM_PORTAL\node_modules\multer\node_modules\busboy\node_modules\dicer\lib\HeaderParser.js:68:8)
```

Jade
```jade
doctype html
html(lang='en')
  head
    title Portal
    script(src="js/lib/angular.js")
    script(src="js/apps/home/homeApp.js")
  body(ng-app="homeApp" )
    - console.log("testing");
    div(ng-controller="homeController") Welcome 
      input(type='file', name='alcon', onchange='angular.element(this).scope().uploadFile(this.files)')
```

homeApp.js
```javascript
var app = angular.module('homeApp', []);

app.controller('homeController', ['$scope', '$http', function($scope, $http){
  $scope.uploadFile = function(files) {
    var fd = new FormData();
    //Take the first selected file
    fd.append("file", files[0]);

    $http.post('/upload', fd, {
        withCredentials: true,
        headers: {'Content-Type': undefined },
        transformRequest: angular.identity,
    }).then(function successCallback(res){
      console.log("Success");
    }, function errorCallback(res){
      console.log("error");
      console.dir(res);
    });
  };
}]);
```

app.js
```javascript
var express = require('express'); 
var path = require('path'); // for Path manipulation
var humanize = require('humanize');
var bodyParser = require('body-parser');
var multer = require('multer');
var upload1  = multer({dest: './uploads'});

var app = express(); // Create server
app
  .set('views', path.join(process.cwd(), 'app/'))
  .set('view engine', 'jade')
  .locals.basedir = app.get('views');

app
  .use(express.static(path.join(process.cwd(), '/www/assets'))) 
  .use(bodyParser.urlencoded({ extended: false }))
  .use(bodyParser.json());

app.use(function (err, req, res, next) {
  console.log("inside use function");
  console.log(err); // <-- this should show you the fieldname of the offending file
  console.log(err.stack);
});

app.get('/home', function(req, res, next){
  res.render('home/home.jade');
});

app.post('/upload', upload1.single('alcon'), function(req, res, next){
  //fileSize = req.headers['content-length'];
  //console.log("upload File Size : " +  humanize.filesize(fileSize));
  //console.log(req.body);
  //console.dir(req);
});

app.listen('3002', function(){ // config application port
  console.log("listening on port 3002");
});
```

**Comment by LinusU** [comment]
Your file is called "file" but your server expects it to be called "alcon".

**Comment by anand-ma** [comment]
@LinusU I'm sorry i dont understand, name='alcon' is specified in input tag and upload1.single('alcon') in app.post. Where my file is called "file" ?

**Comment by LinusU** [comment]
Here:

```javascript
    //Take the first selected file
    fd.append("file", files[0]);
```

**Comment by anand-ma** [comment]
@LinusU Thank you so much, that worked. Didnt release it

**Comment by LinusU** [comment]
No problem :+1:
