### ISSUE TITLE
Calling the middleware function by yourself crashes when no files sent

### ISSUE THREAD

**Issue by speeltronics** [expressjs/multer#300]
I am trying to use multer by calling the upload function myself to catch errors as shown in the ERROR HANDLING part of README.md. The upload works fine when files are selected, but if no files are sent then the program crashes when upload is called. If I do the upload by not calling it myself then it just gives a 500 server error and I get files length of 0. I would assume the same thing should happen if I call upload myself, but it crashes instead. So I assume this is a bug. Is there a way to check if the req contains any files before I call upload? I have searched through the req object, but can't find anything about the files. Any help would be appreciated. Thanks!

**Comment by LinusU** [comment]
Can you post the stack trace from the crash?

**Comment by speeltronics** [comment]
debugger listening on port 5858
======
[]

/home/ubuntu/projects/nodeapps/cmsapp/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:511
    throw toError("Invalid Operation, No operations in bulk");
          ^
MongoError: Invalid Operation, No operations in bulk
    at Function.MongoError.create (/home/ubuntu/projects/nodeapps/cmsapp/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/ubuntu/projects/nodeapps/cmsapp/node_modules/mongoose/node_modules/mongodb/lib/utils.js:114:22)
    at UnorderedBulkOperation.execute (/home/ubuntu/projects/nodeapps/cmsapp/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:511:11)
    at bulkWrite (/home/ubuntu/projects/nodeapps/cmsapp/node_modules/mongoose/node_modules/mongodb/lib/collection.js:592:8)
    at Collection.insertMany (/home/ubuntu/projects/nodeapps/cmsapp/node_modules/mongoose/node_modules/mongodb/lib/collection.js:483:44)
    at Collection.insert (/home/ubuntu/projects/nodeapps/cmsapp/node_modules/mongoose/node_modules/mongodb/lib/collection.js:766:15)
    at NativeCollection.(anonymous function) [as insert] (/home/ubuntu/projects/nodeapps/cmsapp/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:136:28)
    at /home/ubuntu/projects/nodeapps/cmsapp/private/routes/selections.server.routes.js:76:31
    at Object.<anonymous> (/home/ubuntu/projects/nodeapps/cmsapp/node_modules/multer/lib/make-middleware.js:52:37)
    at Object.immediate._onImmediate (timers.js:348:16)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

npm ERR! Linux 3.0.35-g8a6eb06-dirty
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.22
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! cmsserver@0.0.1 start: `node --debug ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the cmsserver@0.0.1 start script 'node --debug ./bin/www'.
npm ERR! This is most likely a problem with the cmsserver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --debug ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls cmsserver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/projects/nodeapps/cmsapp/npm-debug.log

**Comment by LinusU** [comment]
Your error is with the mongodb library which this module doesn't use at all. I believe that the error is somewhere in your code, out of our control...

**Comment by speeltronics** [comment]
Yes, you are right, thank you for your time! It is working now!
