### ISSUE TITLE
req.file is always undefined

### ISSUE THREAD

**Issue by otmeek** [expressjs/multer#324]
This is my first time using multer, so I'm probably missing something, but I'm trying to make it possible to upload a file to the server using post, but req.file is always undefined.
Here is my code:

```
'use strict';

var express = require('express');
var path    = require('path');
var multer  = require('multer')
var upload  = multer({ dest: 'uploads/' })

var app = express();
require('dotenv').load();

app.use(express.static(path.join(__dirname, 'main')));

app.post('/', upload.single('upl'), function (req, res, next) {
  // req.file is the `avatar` file
  // req.body will hold the text fields, if there were any
  console.log(req.file);
  res.status(204).end();
})

var port = process.env.PORT || 8080;
app.listen(port,  function () {
	console.log('Node.js listening on port ' + port + '...');
});
```

and the form:

```
            <form class="uploadForm" action="/" method="post">
                <label class="control-label">Select File</label>
                <input name="upl" id="input-1" type="file" class="file">
            </form>
```

Please let me know what I'm doing wrong. Thank you!

**Comment by LinusU** [comment]
The form needs to have `enctype="multipart/formdata"`, this tells the browser that it should use the multipart content type when uploading.

**Comment by otmeek** [comment]
I added that, and now I get the following

```
Error: Unexpected field
   at makeError (/home/ubuntu/workspace/node_modules/multer/lib/make-error.js:12:13)
   at wrappedFileFilter (/home/ubuntu/workspace/node_modules/multer/index.js:39:19)
   at Busboy.<anonymous> (/home/ubuntu/workspace/node_modules/multer/lib/make-middleware.js:112:7)
   at emitMany (events.js:108:13)
   at Busboy.emit (events.js:182:7)
   at Busboy.emit (/home/ubuntu/workspace/node_modules/multer/node_modules/busboy/lib/main.js:31:35)
   at PartStream.<anonymous> (/home/ubuntu/workspace/node_modules/multer/node_modules/busboy/lib/types/multipart.js:208:13)
   at emitOne (events.js:77:13)
   at PartStream.emit (events.js:169:7)
   at HeaderParser.<anonymous> (/home/ubuntu/workspace/node_modules/multer/node_modules/busboy/node_modules/dicer/lib/Dicer.js:51:16)
```

**Comment by LinusU** [comment]
Can you verify that the input fields name is indeed `upl`, and that there is no other files being uploaded in the form?

**Comment by otmeek** [comment]
Yes the input's name is indeed `upl`. It no longer gives the error, however `req.file` is still undefined :(

Current code:

```
'use strict';

var express = require('express');
var path    = require('path');
var multer  = require('multer')
var upload  = multer({ dest: 'uploads/' })

var app = express();
require('dotenv').load();

app.use(express.static(path.join(__dirname, 'main')));

app.post('/upload', upload.single('upl'), function (req, res, next) {
  // req.file is the `avatar` file
  // req.body will hold the text fields, if there were any
  console.log(req.file);
  res.status(204).end();
})

var port = process.env.PORT || 8080;
app.listen(port,  function () {
    console.log('Node.js listening on port ' + port + '...');
});
```

```
            <form class="uploadForm" action="/upload" method="post" enctype="multipart/formdata">
                <label class="control-label">Select File</label>
                <input name="upl" id="input-1" type="file" class="file">
                <input type="submit" value="submit" />
            </form>
```

**Comment by otmeek** [comment]
Nevermind, I figured it out. enctype is supposed to be `multipart/form-data` and not `multipart/formdata`

**Comment by LinusU** [comment]
Whoops, sorry about that. Glad you got it resolved :+1:
