### ISSUE TITLE
App crashes if received a folder instead of file(s)

### ISSUE THREAD

**Issue by tonghae** [expressjs/multer#355]
I'm using Summernote text editor and its drag&drop to upload feature and noticed that if I drop a folder instead of files it can crash my app:

> events.js:160
>      throw er; // Unhandled 'error' event
>      ^
>Error: Part terminated early due to unexpected end of multipart data
>    at /Users/anubis/node_modules/dicer/lib/Dicer.js:65:36
>    at _combinedTickCallback (internal/process/next_tick.js:67:7)
>    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

My file receive logic (simplified for example):

    var upload = multer({
        dest: config.image.uploadTmpDir,
        limits: {
            fileSize: 1024 * 1024 * 5
        },
        fileFilter: function(req, file, cb) {
            cb(null, file.mimetype.indexOf('image/') == 0);
        }
    });

    // ...

    router.post('/posts/attachments', authorizedToAddPosts, function(req, res) {
        async.series([
            function upl(callback) {
                upload.array('image', 10)(req, res, callback);
            },
            function otherTasks() {
                // ...
            }
        ]);
    });

I don't need to use folder uploading feature itself, but it's not cool to have an opportunity to crash application by simple query.
Thanks for any tips and solutions.

**Comment by LinusU** [comment]
That seems like a bug indeed, I'll try and take a look at this as soon as possible...

**Comment by jesusgp22** [comment]
I found this bug today, I probably sent a badly formed request, multer should be able to handle this because it crashes the whole app

**Comment by Nephos** [comment]
Reproduced here.

I'll try to generate some traces and try to understand what's wrong.
