### ISSUE TITLE
Upload files from 3 different input field

### ISSUE THREAD

**Issue by deepdil-enfin** [expressjs/multer#382]
Hi ,
i have 3 input file fields
< input type="file" name="field1">
< input type="file" name="field2">
< input type="file" name="field3">
field1.single('field1') , field2.single('field2'), field3.single('field3')

Getting Error

Error: Unexpected field
   at makeError (D:\beta_talscout\node_modules\multer\lib\make-error.js:12:13)
   at wrappedFileFilter (D:\beta_talscout\node_modules\multer\index.js:39:19)
   at Busboy.<anonymous> (D:\beta_talscout\node_modules\multer\lib\make-middleware.js:112:7)
   at emitMany (events.js:121:13)
   at Busboy.emit (events.js:195:7)
   at Busboy.emit (D:\beta_talscout\node_modules\busboy\lib\main.js:31:35)
   at PartStream.<anonymous> (D:\beta_talscout\node_modules\busboy\lib\types\multipart.js:213:13)
   at emitOne (events.js:90:13)
   at PartStream.emit (events.js:182:7)
   at HeaderParser.<anonymous> (D:\beta_talscout\node_modules\dicer\lib\Dicer.js:51:16)
   at emitOne (events.js:90:13)
   at HeaderParser.emit (events.js:182:7)
   at HeaderParser._finish (D:\beta_talscout\node_modules\dicer\lib\HeaderParser.js:68:8)
   at SBMH.<anonymous> (D:\beta_talscout\node_modules\dicer\lib\HeaderParser.js:40:12)
   at emitMany (events.js:121:13)
   at SBMH.emit (events.js:195:7)
   at SBMH._sbmh_feed (D:\beta_talscout\node_modules\streamsearch\lib\sbmh.js:159:14)
   at SBMH.push (D:\beta_talscout\node_modules\streamsearch\lib\sbmh.js:56:14)
   at HeaderParser.push (D:\beta_talscout\node_modules\dicer\lib\HeaderParser.js:46:19)
   at Dicer._oninfo (D:\beta_talscout\node_modules\dicer\lib\Dicer.js:197:25)
   at SBMH.<anonymous> (D:\beta_talscout\node_modules\dicer\lib\Dicer.js:127:10)
   at emitMany (events.js:121:13)

**Comment by Runa-Redapple** [comment]
I also get error .any solution??

**Comment by LinusU** [comment]
You can only add the middleware once, so you'll have to use `.fields` instead of `.single`:

https://github.com/expressjs/multer#fieldsfields

```
.fields([
  { name: 'field1', maxCount: 1 },
  { name: 'field2', maxCount: 1 },
  { name: 'field3', maxCount: 1 }
])
```
