### ISSUE TITLE
Not writting file to disk in some machines

### ISSUE THREAD

**Issue by miqmago** [expressjs/multer#428]
Having a very strange issue. I'm running tests in my local machine (OSX 10.11.6) and it all runs fine. I'm running it on a linux amazon EC2 and the file does not get written to disk:

The test:

```js
it('Should be OK if timestamp is not specified in the filename', (done) => {
    doLogin(request(app).post('/pictures')) // It sets the "Authorization: Basic ..." header
        .set('Accept', 'application/json')
        .set('Content-Type', 'multipart/form-data')
        .set('connection', 'keep-alive')
        .attach('picture', path.join(global.basedir, `/mocks/pictures/${p2}`))
        .expect(201, done);
});
```

The handler (`global.basedir = __dirname` in `server.js` main file):

```js
const multer = require('multer');

const storage = multer.diskStorage({
    destination: path.join(global.basedir, '/uploads/'),
    filename: (req, file, cb) => {
        const src = file.originalname;

        req.timestamp = parseInt(src.split(':')[0], 10);
        req.pictureId = src.split('.')[0];

        if (!isDate(req.timestamp)) {
            req.timestamp = new Date().getTime();
        }
	cb(null, src);
    },
});

const upload = multer({ storage });

const router = Router();

/**
 * Pictures /pictures POST
 */
// router.post('/', requireLogin(), upload.single('picture'), uploadPicture);
router.post('/', requireLogin(), (req, res, next) => {
    console.log('uploading picture...', req.headers);
    upload.single('picture')(req, res, (err) => {
        if (err) console.log('Error uploading picture!', err);
        else console.log('success!');
        next(err);
    });
}, uploadPicture);
```

uploadPicture tries to generate a thumbnail but it does not find the file and fails with 500 which makes the test to fail:

```js
/**
 * Upload picture
 */
export const uploadPicture = (req, res) => {
    const userId = req.user.id;
    const { filename } = req.file;
    const { pictureId, timestamp } = req;

    const throwError = (err) => {
        if (filename) removePictureFromDiskSync(filename);
        res.status(500).send(err);
    };

    console.log('Generating thumbnail and inserting to db...', req.file);
    if (userId && filename) {
        Promise.all([
            generateThumbnail(filename),
            insertPicture(pictureId, userId, filename, timestamp),
        ])
            .then(() => res.status(201).jsonp({ pictureId }))
            .catch(throwError);
    } else {
	throwError();
    }
};
```

The results in EC2 instance (not working):

```
    /pictures POST
uploading picture... { host: '127.0.0.1:39641',
  'accept-encoding': 'gzip, deflate',
  'user-agent': 'node-superagent/2.3.0',
  authorization: 'Basic NTU0YTBjOWQtODU1My00NTFkLWJ...',
  'x-nonce': 'ABC',
  'x-timestamp': '1481219264.375',
  accept: 'application/json',
  'content-type': 'multipart/form-data; boundary=--------------------------880012344979595151310602',
  connection: 'keep-alive',
  'content-length': '33415' }
success!
Generating thumbnail and inserting to db... { fieldname: 'picture',
  originalname: '1480942702560:dec8768e-3c63-4b69-9961-4c83de3f6e6c.jpg',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  destination: '/mnt/data/server/uploads/',
  filename: '1480942702560:dec8768e-3c63-4b69-9961-4c83de3f6e6c.jpg',
  path: '/mnt/data/server/uploads/1480942702560:dec8768e-3c63-4b69-9961-4c83de3f6e6c.jpg',
  size: 33160 }
2016-12-08T17:47:44.432Z POST /pictures 500 44.992 ms - 2
(node:23473) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: ENOENT: no such file or directory, access '/mnt/data/server/uploads/1480942702560:dec8768e-3c63-4b69-9961-4c83de3f6e6c_thumb.jpg'
      1) Should be OK if timestamp is not specified in the filename:
     Error: expected 201 "Created", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:266:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:281:11)
      at Test.assert (node_modules/supertest/lib/test.js:171:18)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1548:8)
      at _combinedTickCallback (internal/process/next_tick.js:71:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

The results in local machine (it's working):

```
  Pictures
    /pictures POST
uploading picture... { host: '127.0.0.1:50650',
  'accept-encoding': 'gzip, deflate',
  'user-agent': 'node-superagent/2.3.0',
  authorization: 'Basic NTU0YTBjOWQtODU1My00NTFkLWJ...',
  'x-nonce': 'ABC',
  'x-timestamp': '1481218651.177',
  accept: 'application/json',
  'content-type': 'multipart/form-data; boundary=--------------------------772308738869310824844451',
  connection: 'keep-alive',
  'content-length': '33415' }
success!
Generating thumbnail and inserting to db... { fieldname: 'picture',
  originalname: '1480942702560:dec8768e-3c63-4b69-9961-4c83de3f6e6c.jpg',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  destination: '/Users/miqmago/Apps/pictures-server/uploads/',
  filename: '1480942702560:dec8768e-3c63-4b69-9961-4c83de3f6e6c.jpg',
  path: '/Users/miqmago/Apps/pictures-server/uploads/1480942702560:dec8768e-3c63-4b69-9961-4c83de3f6e6c.jpg',
  size: 33160 }
2016-12-08T17:37:32.626Z POST /pictures 201 1431.427 ms - 66
      ✓ Should be OK if timestamp is not specified in the filename (1451ms)
```

**Comment by miqmago** [comment]
Remote machine info:

`/mnt/data/server/uploads/` is owned by `ec2-user` (the one that is running tests) and it has 777 permission.

```
Linux 4.4.16-27.56.amzn1.x86_64 x86_64

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
Stepping:              4
CPU MHz:               2500.060
BogoMIPS:              5000.12
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0
```

**Comment by miqmago** [comment]
Sorry, it was a problem of imagemagick dependencies when generating thumbnail
