### ISSUE TITLE
error information

### ISSUE THREAD

**Issue by okfirelee** [expressjs/multer#467]
Express
500 Error: Buffer.write(string, encoding, offset[, length]) is no longer supported

    at Buffer.write (buffer.js:732:11)
    at MultipartParser.initWithBoundary (/leelinuxbj/node/file/upload/node_modules/formidable/lib/multipart_parser.js:61:17)
    at IncomingForm._initMultipart (/leelinuxbj/node/file/upload/node_modules/formidable/lib/incoming_form.js:308:10)
    at IncomingForm._parseContentType (/leelinuxbj/node/file/upload/node_modules/formidable/lib/incoming_form.js:250:12)
    at IncomingForm.writeHeaders (/leelinuxbj/node/file/upload/node_modules/formidable/lib/incoming_form.js:129:8)
    at IncomingForm.parse (/leelinuxbj/node/file/upload/node_modules/formidable/lib/incoming_form.js:97:8)
    at exports.upload (/leelinuxbj/node/file/upload/routes/upload.js:43:7)
    at callbacks (/leelinuxbj/node/file/upload/node_modules/express/lib/router/index.js:164:37)
    at param (/leelinuxbj/node/file/upload/node_modules/express/lib/router/index.js:138:11)
    at pass (/leelinuxbj/node/file/upload/node_modules/express/lib/router/index.js:145:5)

**Comment by LinusU** [comment]
It seems like you are using `formidable`, and not `multer` :)
