### ISSUE TITLE
Unknown Exception

### ISSUE THREAD

**Issue by salman-pathan** [expressjs/multer#498]
Well I'm trying to make a simple HTTP server which accepts Image, but I'm getting the below exception. My other REST routes are working fine, I'm only facing the issue when I hit the below route.

**Exception**
```
at readStream (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/raw-body/index.js:196:17)
    at getRawBody (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/raw-body/index.js:106:12)
    at read (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/body-parser/lib/read.js:76:3)
    at urlencodedParser (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/body-parser/lib/types/urlencoded.js:115:5)
    at Layer.handle [as handle_request] (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/router/index.js:317:13)
    at /Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/router/index.js:317:13)
    at /Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/salmankhan/Documents/Codiodes/pocApi/node_modules/express/lib/middleware/query.js:44:5)
```

**Code**
```
var express    = require('express');
var app        = express();
var bodyParser = require('body-parser');
var mongoose   = require('mongoose');
var morgan     = require ('morgan');
var multer     = require('multer');
var upload     = multer();

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

var port = process.env.PORT || 8080;

app.post('/api/upload', upload.single('pp'), function(req, res) {
    console.log(req);
});
app.listen(port);
```

**Framework**
```
Node : v8.0.0
npm : 5.0.0
```

**Comment by LinusU** [comment]
It seems like this is happening before control is handed over to multer, could you try commenting out the two following lines to isolate the problem?

```
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
```

**Comment by jonchurch** [comment]
Closing as inactive
