### ISSUE TITLE
Unexpected field after match between input name and multer.single

### ISSUE THREAD

**Issue by emilhamep** [expressjs/multer#517]
I know that this question already asked many times, but after I looked the answers of existing issues still doens't work in my code. I'm using multer 1.3.0. My snippet code as follows:

**Router**
```
var multer = require('multer'),
	bodyParser = require('body-parser'),
	path = require('path');

router.post("/kegiatan", multer({ dest: './uploads/'}).single('foto'), siswa_controller.tambah_kegiatan);
```

**View**
```
form.ui.form(method='post',action='/member/siswa/kegiatan', enctype='multipart/form-data')
      .field
        label Judul Kegiatan
        input(type='text', name='judul', placeholder='Tuliskan judul kegiatan')
      .field
        label Kategori
        select.ui.search.dropdown(name='kategori',id='selectKategori')
              option(value='') Pilih kategori kegiatan              
      .field
        label Berkas Foto
        input(type='file',name='foto')
```

**Comment by LinusU** [comment]
Could you post the exact error that you get?

**Comment by emilhamep** [comment]
@LinusU The message as shown below
```
Unexpected field

Error: Unexpected field
    at makeError (/Users/Ilham/Documents/ProjectDeskop/Vd/vidyanusa-layer-3-4/node_modules/multer/lib/make-error.js:12:13)
    at wrappedFileFilter (/Users/Ilham/Documents/ProjectDeskop/Vd/vidyanusa-layer-3-4/node_modules/multer/index.js:40:19)
    at Busboy.<anonymous> (/Users/Ilham/Documents/ProjectDeskop/Vd/vidyanusa-layer-3-4/node_modules/multer/lib/make-middleware.js:114:7)
    at emitMany (events.js:146:13)
    at Busboy.emit (events.js:223:7)
    at Busboy.emit (/Users/Ilham/Documents/ProjectDeskop/Vd/vidyanusa-layer-3-4/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/Users/Ilham/Documents/ProjectDeskop/Vd/vidyanusa-layer-3-4/node_modules/busboy/lib/types/multipart.js:213:13)
    at emitOne (events.js:115:13)
    at PartStream.emit (events.js:210:7)
    at HeaderParser.<anonymous> (/Users/Ilham/Documents/ProjectDeskop/Vd/vidyanusa-layer-3-4/node_modules/dicer/lib/Dicer.js:51:16)
    at emitOne (events.js:115:13)
    at HeaderParser.emit (events.js:210:7)
    at HeaderParser._finish (/Users/Ilham/Documents/ProjectDeskop/Vd/vidyanusa-layer-3-4/node_modules/dicer/lib/HeaderParser.js:68:8)
    at SBMH.<anonymous> (/Users/Ilham/Documents/ProjectDeskop/Vd/vidyanusa-layer-3-4/node_modules/dicer/lib/HeaderParser.js:40:12)
    at emitMany (events.js:146:13)
    at SBMH.emit (events.js:223:7)
```

**Comment by LinusU** [comment]
Which browser are you using? Would it be possible to capture the request in Chrome/Safari Dev Tools or something similar?

**Comment by emilhamep** [comment]
@LinusU  I'm using Chrome, following is the capture for request using Chrome Network tab when I send POST request with input file: [here](https://ibb.co/c0wuBa)

**Comment by LinusU** [comment]
I think that if you click the request you can see the request body. Here we should be able to see the field name of the file. This should tell us wether the problem is on the server side, or the client side.

**Comment by emilhamep** [comment]
Finally, I've solved the problem. I didn't realize that I wrote twice for require multer(In controller and app.js). So should be sure that just once to write require the multer library. In my case just in controller and it works to upload file. 
And for parsing file request just type req.file not req.foto in my case.

Sorry for my fault, Thank you anyway @LinusU

**Comment by nguyencongvu** [comment]
> Finally, I've solved the problem. I didn't realize that I wrote twice for require multer(In controller and app.js). So should be sure that just once to write require the multer library. In my case just in controller and it works to upload file.
> And for parsing file request just type req.file not req.foto in my case.
> 
> Sorry for my fault, Thank you anyway @LinusU

I spent all days to check and got same stupid mistake as you. 
For one who got "Unexpected field" error although fieldname matched (or KEY in Postman matched), please check again in your app.js (or main.js..) whether you declare and init Multer before 

Thanks
