### ISSUE TITLE
Crashes randomly after Uploading

### ISSUE THREAD

**Issue by sean-macfarlane** [expressjs/multer#540]
After uploading a file it will crash randomly with this error 

```
C:\Bitnami\meanstack-3.4.6-0\MortgageApp\node_modules\on-finished\index.js:96
    eeMsg.cancel()
          ^

TypeError: eeMsg.cancel is not a function
    at onFinish (C:\Bitnami\meanstack-3.4.6-0\MortgageApp\node_modules\on-finished\index.js:96:11)
    at cleanup (C:\Bitnami\meanstack-3.4.6-0\MortgageApp\node_modules\ee-first\index.js:41:10)
    at IncomingMessage.onevent (C:\Bitnami\meanstack-3.4.6-0\MortgageApp\node_modules\ee-first\index.js:58:5)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

backend code: 

```
const fileSizeLimit = 209715200; // 200MB
const uploadFolder = './public/uploads';
var upload = multer({ 
    limits: { fileSize: fileSizeLimit },
    dest: uploadFolder
});

var router = express.Router();

const storage = multer.diskStorage({
    destination: uploadFolder,
    filename: function (req, file, callback) {
        callback(null, file.fieldname + "_" + Date.now() + "_" + file.originalname);
    }
});

const uploader = multer({
    limits: { fileSize: fileSizeLimit },
    storage: storage
});

var upload = uploader.array('file');

router.post('/processDL', function(req, res) {
	upload(req, res, function (err) {
	      console.log("ERROR1:");
	      console.log(err);
              return res.status(200).json({});
  });
});

router.post('/processDL/:id', function(req, res) {
	upload(req, res, function (err) {
	      console.log("ERROR2:");
	      console.log(err);
              return res.status(200).json({});
  })
});

```

**Comment by HarshithaKP** [comment]
@sean-macfarlane Is this issues still exists ??. If yes, can you please provide the versions of Express, Multer and Node.js

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
