### ISSUE TITLE
How do I prevent issue #159 / #454 from being used maliciously to crash my server?

### ISSUE THREAD

**Issue by NobleUplift** [expressjs/multer#544]
So I also fell prey to bugs #159 and #454 by having a mismatch between the fieldname in my HTML vs. in my API.

What I want to know is: how do I capture this error and prevent it from crashing my server? Nowhere in the exception log does it show a line of my code, and I'm loading Multer into Express' Router as a callback function, so I don't see where I would put the try/catch.

As I see it, someone could change the value of the field in HTML, submit the form, and then cause my application to crash. This isn't something I would go into a production environment with knowing that it exists.

```
{}
{}
{ Error: Unexpected field
    at makeError (/Library/WebServer/adstudio/node_modules/multer/lib/make-error.js:12:13)
    at wrappedFileFilter (/Library/WebServer/adstudio/node_modules/multer/index.js:40:19)
    at Busboy.<anonymous> (/Library/WebServer/adstudio/node_modules/multer/lib/make-middleware.js:114:7)
    at emitMany (events.js:127:13)
    at Busboy.emit (events.js:204:7)
    at Busboy.emit (/Library/WebServer/adstudio/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/Library/WebServer/adstudio/node_modules/busboy/lib/types/multipart.js:213:13)
    at emitOne (events.js:96:13)
    at PartStream.emit (events.js:191:7)
    at HeaderParser.<anonymous> (/Library/WebServer/adstudio/node_modules/dicer/lib/Dicer.js:51:16)
    at emitOne (events.js:96:13)
    at HeaderParser.emit (events.js:191:7)
    at HeaderParser._finish (/Library/WebServer/adstudio/node_modules/dicer/lib/HeaderParser.js:68:8)
    at SBMH.<anonymous> (/Library/WebServer/adstudio/node_modules/dicer/lib/HeaderParser.js:40:12)
    at emitMany (events.js:127:13)
    at SBMH.emit (events.js:204:7)
    at SBMH._sbmh_feed (/Library/WebServer/adstudio/node_modules/streamsearch/lib/sbmh.js:159:14)
    at SBMH.push (/Library/WebServer/adstudio/node_modules/streamsearch/lib/sbmh.js:56:14)
    at HeaderParser.push (/Library/WebServer/adstudio/node_modules/dicer/lib/HeaderParser.js:46:19)
    at Dicer._oninfo (/Library/WebServer/adstudio/node_modules/dicer/lib/Dicer.js:197:25)
    at SBMH.<anonymous> (/Library/WebServer/adstudio/node_modules/dicer/lib/Dicer.js:127:10)
    at emitMany (events.js:127:13)
  code: 'LIMIT_UNEXPECTED_FILE',
  field: 'files[]',
  storageErrors: [] }
_http_server.js:195
    throw new RangeError(`Invalid status code: ${statusCode}`);
    ^

RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:195:11)
    at ServerResponse.writeHead (/Library/WebServer/adstudio/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/Library/WebServer/adstudio/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:159:8)
    at ServerResponse.end (_http_outgoing.js:621:10)
    at writeend (/Library/WebServer/adstudio/node_modules/express-session/index.js:261:22)
    at Immediate.ontouch (/Library/WebServer/adstudio/node_modules/express-session/index.js:348:11)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by LinusU** [comment]
Multer uses standard express error handling, and it seems like the error here is actually due to some error handler trying to set the http status code to `0`.

It's hard to say what exactly it is in you specific app without taking a look at the source. But if you follow the [information on "Error handling"](https://github.com/expressjs/multer#error-handling) in the readme you should be able to gracefully handle them and send back error pages to the client.

Unfortunately the stack trace doesn't seem to show where `writeHead` was originally called since `on-headers` shims it... Do you have any global error-handeling middleware added? I think that's where the culprit is...

**Comment by LinusU** [comment]
(I'll close this since the error isn't in Multer, but I'll be very happy to further assist you in solving this here!)

**Comment by NobleUplift** [comment]
Thanks a lot Linus! I had the [errorhandler](https://www.npmjs.com/package/errorhandler) in my app.use, but it seems like it was being hit before my Multer route defined in the Express Router. I added a route.use(errorhandler()) to the route and it catches errors correctly now.

**Comment by LinusU** [comment]
Great!
