### ISSUE TITLE
i'm trying to save a file in my server

### ISSUE THREAD

**Issue by fahdaddi** [expressjs/multer#571]
`const express = require('express');
const route = express.Router();
const multer  = require('multer');
//const upload = multer({ dest: 'upload/' });

var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, '../upload')
  },
  filename: function (req, file, cb) {
    cb(null, file.fieldname + '-' + Date.now()+".jpg")
  }
})

var upload = multer({ storage: storage }).single('sampleFile')

//route.use(upload());
route.get("/upload",(req,res,next)=>{
  res.render("siteshs/upload");
});

route.post('/upload', function (req, res,next) {
  upload(req, res, function (err) {
    if (err) {
      // An error occurred when uploading
      return
    }
    console.log(req.files.sampleFile);
    // Everything went fine
  })
})
module.exports = route
`

the PUG code 
`
extends ../layout

block content
  form(method="post", action="/siteshs/upload")
    .form-group
      label  choisissez votre fichier excel
      input.form-control(type='file', name='sampleFile')
    .form-group
      input.form-control(type="submit", value="envoyer")
`

i'm getting the following error:
TypeError: Cannot read property 'sampleFile' of undefined
    at C:\Users\fahd\Desktop\STAGE PFE\routes\siteshs.js:36:26
    at multerMiddleware (C:\Users\fahd\Desktop\STAGE PFE\node_modules\multer\lib\make-middleware.js:18:41)
    at C:\Users\fahd\Desktop\STAGE PFE\routes\siteshs.js:31:3
    at Layer.handle [as handle_request] (C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\fahd\Desktop\STAGE PFE\node_modules\express\lib\router\index.js:335:12)

**Comment by LinusU** [comment]
Since you are using `.single(...)` you want to access `req.file`, instead of `req.files.sampleFile`.
