### ISSUE TITLE
Breaking Node For some files without a log catch

### ISSUE THREAD

**Issue by mariohmol** [expressjs/multer#584]
Hi,

thanks for awesome module!

This is working pretty much everything, but for some files (WAV) i'm getting an error.

The problem is that i cant catch the error, it breaks the node app.

I tryed using onError but is not triggering.. even then express main erorr router is not called `app.use((error, req, res, next) => {`

Any ideas on how i can go further to find what is the root cause, or to guarantee that does not break node.

```
 "stack": [
    "Error: eventTask 'Busboy.addListener:finish': can not transition to 'running', expecting state 'scheduled', was 'notScheduled'.",
    "    at new Error (native)",
    "    at ZoneTask._transitionTo (/v2/web/node_modules/zone.js/dist/zone-node.js:495:23) [<root>]",
    "    at Zone.runTask (/v2/web/node_modules/zone.js/dist/zone-node.js:155:34) [<root>]",
    "    at Busboy.ZoneTask.invoke (/v2/web/node_modules/zone.js/dist/zone-node.js:460:38) [<root>]",
    "    at emitNone (events.js:91:20) [<root>]",
    "    at Busboy.emit (events.js:185:7) [<root>]",
    "    at Busboy.emit (/v2/web/node_modules/busboy/lib/main.js:38:33) [<root>]",
    "    at /v2/web/node_modules/busboy/lib/types/multipart.js:52:13 [<root>]",
    "    at data.args.(anonymous function) (/v2/web/node_modules/zone.js/dist/zone-node.js:1598:25) [<root>]",
    "    at _combinedTickCallback (internal/process/next_tick.js:73:7) [<root>]",
    "    at process._tickCallback (internal/process/next_tick.js:104:9) [<root>]"
  ],
  "level": "error",
  "message": "uncaughtException: eventTask 'Busboy.addListener:finish': can not transition to 'running', expecting state 'scheduled', was 'notScheduled'."
```

**Comment by LinusU** [comment]
Interesting, this is not good 🤔 

Would you mind opening an issue here: https://github.com/mscdex/busboy

Thanks

**Comment by mariohmol** [comment]
Will keep investigating on zone.js, thanks!
