### ISSUE TITLE
Kindly please help me on my problem in nodejs. Whenever I try to excecute my server.js I'am prompted with the following error shown below:

### ISSUE THREAD

**Issue by Marvaahh** [expressjs/multer#615]
H:\LoginNode>node server
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module './types/multipart'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (H:\LoginNode\node_modules\multer\node_modules\busboy\lib\main.js:85:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

**Comment by LinusU** [comment]
How does your package.json look? Did you run `npm install`?

**Comment by dougwilson** [comment]
Closing due to no response.
