### ISSUE TITLE
Error - csurf with multer 

### ISSUE THREAD

**Issue by dsalcedo** [expressjs/multer#71]
Hello, im using csrf module (csurf) but when im uploading...
```text
Error: invalid csrf token
   at verifytoken (D:\nodejs\node_modules\csurf\index.js:234:13)
   at csrf (D:\nodejs\node_modules\csurf\index.js:94:7)
   at Layer.handle [as handle_request] (D:\nodejs\node_modules\express\lib\router\layer.js:76:5)
   at trim_prefix (D:\nodejs\node_modules\express\lib\router\index.js:263:13)
   at D:\nodejs\node_modules\express\lib\router\index.js:230:9
   at Function.proto.process_params (D:\nodejs\node_modules\express\lib\router\index.js:305:12)
   at D:\nodejs\node_modules\express\lib\router\index.js:221:12
   at Function.match_layer (D:\nodejs\node_modules\express\lib\router\index.js:288:3)
   at next (D:\nodejs\node_modules\express\lib\router\index.js:182:10)
   at methodOverride (D:\nodejs\node_modules\method-override\index.js:77:5)`
```
var product=config.upload;
```javascript
 uri.route('/up').get(function (req,res,next) {
              res.render('upload',{
                csrf  : req.csrfToken()
              });
              res.end();
      }).post(product,function  (req,res,next) {
        console.log('IN POST (/upload)');
        console.log(req.body)
        var filesUploaded = 0;
        if ( Object.keys(req.files).length === 0 ) {
            console.log('no files uploaded');
        } else {
            console.log(req.files)

            var files = req.files.file1;
            if (!util.isArray(req.files.file1)) {
                files = [ req.files.file1 ];
            } 

            filesUploaded = files.length;
        }
        res.json({ message: 'Finished! Uploaded ' + filesUploaded + ' files.  Route is /upload' });
      });
```
:hammer:

**Comment by martijngastkemper** [comment]
The fix by @mmnehc works for me, but it's not very nice.

**Comment by dsalcedo** [comment]
You're absolutely right @martijngastkemper , im working in one fork from "multer"  to change this

**Comment by LinusU** [comment]
Make sure that multer is added *before* the csurf middleware, like so:

```javascript
app.use(multer())
app.use(csurf())
```

As far as I can tell it really should work then.

**Comment by alvarotrigo** [comment]
Now there's no longer a use of `app.use`. 
But just : 

    multer({ 
        dest: 'uploads/' 
    });

How should we solve the issue with csrf now?

**Comment by alvarotrigo** [comment]
Fine, found the solution:

```javascript
upload = multer({ 
    dest: 'uploads/' 
});

app.use(upload.single('demo'));
```

**Comment by jarangseo** [comment]
In my case, I added `<input type="hidden" name="_csrf" value="<%=csrfToken%>" />` this input tag in the form tag. So the result will be like below.
```<form action="" method="post" enctype="multipart/form-data">
<input type="hidden" name="_csrf" value="<%=csrfToken%>" />
<table>
<tr>
<th>thumbnail</th>
<td>
<input type="file" name="thumbnail" />
<% if(product.thumbnail){ %>
<a href="/uploads/<%=product.thumbnail%>" target="_blank">preview upload image</a>
<% } %>
</td>
</tr>
</table>
</form>
