### ISSUE TITLE
How to pass the request in SOAPUI or any other API testing IDE ?

### ISSUE THREAD

**Issue by Neseek77** [expressjs/multer#745]
![Screen Shot 2019-06-11 at 1 11 24 pm](https://user-images.githubusercontent.com/13345837/59252811-834f6d80-8c4a-11e9-938b-5d0b0cc1fe75.png)

Receiving this exception, while testing the api in SOAPUI. But it is working from a project. It'd be helpful if there is a way to pass valid request in SOAPUI or any other platform.

**Comment by Neseek77** [comment]
MulterError: Unexpected field
    at wrappedFileFilter (/Users/macbookpro/Desktop/customer-loyalty-program-master/web-app/node_modules/multer/index.js:40:19)
    at Busboy.<anonymous> (/Users/macbookpro/Desktop/customer-loyalty-program-master/web-app/node_modules/multer/lib/make-middleware.js:114:7)
    at emitMany (events.js:147:13)
    at Busboy.emit (events.js:224:7)
    at Busboy.emit (/Users/macbookpro/Desktop/customer-loyalty-program-master/web-app/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/Users/macbookpro/Desktop/customer-loyalty-program-master/web-app/node_modules/busboy/lib/types/multipart.js:213:13)
    at emitOne (events.js:116:13)
    at PartStream.emit (events.js:211:7)
    at HeaderParser.<anonymous> (/Users/macbookpro/Desktop/customer-loyalty-program-master/web-app/node_modules/dicer/lib/Dicer.js:51:16)
    at emitOne (events.js:116:13)

I know this error is because of the 'name' mismatch.
If I try to name the request without an image file attached in the request, the API works but the "req.file" remains undefined.

Any work around for this issue.

**Comment by HarshithaKP** [comment]
@Neseek77 https://github.com/expressjs/multer/issues/307#issuecomment-175652981 explained how to pass the request from postman.

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces

**Comment by Neseek77** [comment]
> @Neseek77 [#307 (comment)](https://github.com/expressjs/multer/issues/307#issuecomment-175652981) explained how to pass the request from postman.

Yes, I have used postman to check these kind of APIs after posting this issue and it worked well.
Thanks
