### ISSUE TITLE
Can't upload file one by one using multer

### ISSUE THREAD

**Issue by sonai95** [expressjs/multer#764]
Whenever I am trying to upload multiple file not at once but one after the other, first file gets uploaded but the second file does not and the error arises like: 
ERROR { MulterError: Unexpected field
    at wrappedFileFilter (/home/suvadeep/Desktop/pharma_portal/node_modules/multer/index.js:40:19)
    at Busboy.<anonymous> (/home/suvadeep/Desktop/pharma_portal/node_modules/multer/lib/make-middleware.js:114:7)
    at emitMany (events.js:147:13)
    at Busboy.emit (events.js:224:7)
    at Busboy.emit (/home/suvadeep/Desktop/pharma_portal/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/home/suvadeep/Desktop/pharma_portal/node_modules/busboy/lib/types/multipart.js:213:13)
    at emitOne (events.js:116:13)
    at PartStream.emit (events.js:211:7)
    at HeaderParser.<anonymous> (/home/suvadeep/Desktop/pharma_portal/node_modules/dicer/lib/Dicer.js:51:16)
    at emitOne (events.js:116:13)
    at HeaderParser.emit (events.js:211:7)
    at HeaderParser._finish (/home/suvadeep/Desktop/pharma_portal/node_modules/dicer/lib/HeaderParser.js:68:8)
    at SBMH.<anonymous> (/home/suvadeep/Desktop/pharma_portal/node_modules/dicer/lib/HeaderParser.js:40:12)
    at emitMany (events.js:147:13)
    at SBMH.emit (events.js:224:7)
    at SBMH._sbmh_feed (/home/suvadeep/Desktop/pharma_portal/node_modules/streamsearch/lib/sbmh.js:159:14)
  name: 'MulterError',
  message: 'Unexpected field',
  code: 'LIMIT_UNEXPECTED_FILE',
  storageErrors: [] }

**Comment by gireeshpunathil** [comment]
@sonai95 - can you please share a minimal test case that shows the issue?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
