### ISSUE TITLE
MulterError: Unexpected field

### ISSUE THREAD

**Issue by nicolas15000** [expressjs/multer#802]
Hello, 

I need to do multiples files uploads with vue.js 2.0 and multer .

I've followed this doc for multiple uploads : 
https://serversideup.net/uploading-files-vuejs-axios/

This is my vue template : 

    <label>Files
        <input name="streamfile" type="file" id="files" ref="files" multiple @change="handleFileUploads" />
    </label>
    <a v-on:click="submitFiles" class="btn btn-primary">Submit</a>

My axios query is the same as in the doc .

This is my multer code :

    var upload = multer({ dest: "uploads/" });
    app.post("/files", upload.array("streamfile", 50), function(req, res, next) {
      console.log(req.files); // []
      console.log(req.body);
      var file = req.files;
      console.log(file);
      res.end();
    });

I 'm getting this error :

    MulterError: Unexpected field
        at wrappedFileFilter (C:\UwAmp\www\vue-starter-webpack-cli-4-node\node_modules\multer\index.js:40:19)
        at Busboy.<anonymous> (C:\UwAmp\www\vue-starter-webpack-cli-4-node\node_modules\multer\lib\make-middleware.js:114:7)
        at Busboy.emit (events.js:189:13)
        at Busboy.emit (C:\UwAmp\www\vue-starter-webpack-cli-4-node\node_modules\busboy\lib\main.js:38:33)
        at PartStream.<anonymous> (C:\UwAmp\www\vue-starter-webpack-cli-4-node\node_modules\busboy\lib\types\multipart.js:213:13)
        at PartStream.emit (events.js:189:13)
        at HeaderParser.<anonymous> (C:\UwAmp\www\vue-starter-webpack-cli-4-node\node_modules\dicer\lib\Dicer.js:51:16)
        at HeaderParser.emit (events.js:189:13)
        at HeaderParser._finish (C:\UwAmp\www\vue-starter-webpack-cli-4-node\node_modules\dicer\lib\HeaderParser.js:68:8)
        at SBMH.<anonymous> (C:\UwAmp\www\vue-starter-webpack-cli-4-node\node_modules\dicer\lib\HeaderParser.js:40:12)

The single upload is working well, i've removed it to avoid any conflict .

The files gets correctly imported in the front end  :

    File { name: "Builder.png", lastModified: 1571932750271, webkitRelativePath: "", size: 821185, type: "image/png" }
    Uploadfiles.vue:52
    File { name: "classic-music.png", lastModified: 1573131217357, webkitRelativePath: "", size: 4073, type: "image/png" }
    Uploadfiles.vue:52
    File { name: "dossier.pdf", lastModified: 1571842341052, webkitRelativePath: "", size: 320949, type: "application/pdf" }
    Uploadfiles.vue:52

EDIT 2 : 

I've changed the code like this : 

vue : 
```
submitFiles : function() {
         
            /*
                    Initialize the form data
                */
            let formData = new FormData();

            /*
            Iteate over any file sent over appending the files
            to the form data.
            */
            for (var i = 0; i < this.files.length; i++) {
              
               let file = this.files[i];

                formData.append('files[' + i + ']', file);
            }
            /*
                Make the request to the POST /multiple-files URL
                */

                axios.post(this.server + 'files',
                    formData, {
                      
                        headers: {
                            'Content-Type': 'multipart/form-data'
                        }
                    }
                ).then(function (response) {
                    console.log(response);

                    // Send to parent component
                    // this.$emit('filename', response.data)
                })
                .catch(function (error) {
                    console.log(error);

                });

        }
```

And the Multer code like that : 
```
var upload = multer({ dest: "./uploads/" });

app.post("/files", upload.array("files"), function(req, res, next) {
  console.log(JSON.stringify(req.files)); // []
});
```

Still the same error .
`MulterError: Unexpected field
`

**Comment by nicolas15000** [comment]
***Edit :*** 

As long as I send only one file, it works :

**Vue.js :**

    var formData = new FormData();
    formData.append('file',this.files[0]);
    axios.post(this.server + 'files',
                        formData, {
                            headers: {
                                'Content-Type': 'multipart/form-data'
                            }
                        }
                    ).then(function (response) {
                    })
                    .catch(function (error) {
                    });
       

**Node.js :**

    var upload = multer({ dest: "uploads/" });
    
        app.post("/files", upload.array("file", 10), function(req, res, err) {
          if (err) {
            console.log(err);
          }
          req.files.forEach(function(file) {
            console.log(file);
          });
        });

As long as I'm trying to send an array, it won't work, and throws **MulterError: Unexpected field** !

    formData.append(file[0],this.files[0]);

**Comment by nicolas15000** [comment]
**Resolved : In case somebody has the problem , it was annoying !:**

This is my vue.js 2.0 code now , **Please notice 'Content-Type': 'undefined'**:

    var formData = new FormData(); 
    for (var i = 0; i < this.files.length; i++) {
        var file = this.files[i];
        formData.append('file', file);
    }
    axios.post(this.server + 'files',
        formData, {
            headers: { crossdomain: true,
                'Content-Type': 'undefined'
            }
        }
    ).then(function (response) {
    })
    .catch(function (error) {
    });


and my node.js code :

    var storageFiles = multer.diskStorage({
      destination: function(req, file, cb) {
        cb(null, "./uploads/files");
      },
      filename: function(req, file, cb) {
        let ext = file.originalname.substring(
          file.originalname.lastIndexOf("."),
          file.originalname.length
        );
        cb(null, file.originalname + "-" + Date.now() + ext);
      }
    });
    
    var uploadFiles = multer({ storage: storageFiles });
    
    
    app.post("/files", uploadFiles.array("file", 10), function(req, res, err) {
      if (err) {
        console.log(err);
      }
    });
