### ISSUE TITLE
Not finding boundary

### ISSUE THREAD

**Issue by jhihn** [expressjs/multer#83]
I'm new to multer, but not hew to HTTP.

```
POST /files HTTP/1.1
Content-Type: multipart/form-data; boundary="boundary_.oOo._MTcyNTgxMTE3Mw==MjEzOTYyMjcyNw==MjA3NTQ2ODA3NQ=="
MIME-Version: 1.0
Content-Length: 186943
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en-US,*
User-Agent: Mozilla/5.0
Host: localhost:10001

--boundary_.oOo._MTcyNTgxMTE3Mw==MjEzOTYyMjcyNw==MjA3NTQ2ODA3NQ==
Content-Type: image/jpeg
Content-Disposition: form-data; name="file"; filename="b9d27cf0-c833-4b93-91c7-6b3c0975e5fb.jpg"

<binary data follows>
```

I'm getting 

```

Error: Multipart: Boundary not found
    at new Multipart (/home/jason/node/dyn/node_modules/multer/node_modules/busboy/lib/types/multipart.js:58:11)
    at Multipart (/home/jason/node/dyn/node_modules/multer/node_modules/busboy/lib/types/multipart.js:26:12)
    at Busboy.parseHeaders (/home/jason/node/dyn/node_modules/multer/node_modules/busboy/lib/main.js:62:22)
    at new Busboy (/home/jason/node/dyn/node_modules/multer/node_modules/busboy/lib/main.js:21:10)
    at /home/jason/node/dyn/node_modules/multer/index.js:51:20
    at Layer.handle [as handle_request] (/home/jason/node/dyn/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/home/jason/node/dyn/node_modules/express/lib/router/index.js:271:13)
    at /home/jason/node/dyn/node_modules/express/lib/router/index.js:238:9
    at Function.proto.process_params (/home/jason/node/dyn/node_modules/express/lib/router/index.js:313:12)
    at /home/jason/node/dyn/node_modules/express/lib/router/index.js:229:12
```

No idea why. Can someone recommend how to debug this? Or why it is not working?

**Comment by anmolgupta** [comment]
I tried it without nginx, but still it is creating a problem

**Comment by LinusU** [comment]
If body-parser is parsing the body before multer, than multer has nothing to parse. Can you try without body-praser?

**Comment by arniroman** [comment]
i have also this problem, i don't know why i receive" Error: Multipart: Boundary not found in my server"
