### ISSUE TITLE
Cannot pass variable in upload.single(fieldName)

### ISSUE THREAD

**Issue by yadirhb** [expressjs/multer#834]
I'm trying to implement a middleware using multer as this code and trying to dynamically create a single uploader passing the name of the field. If I use a variable like in the sample, it fails but if I pass a direct string it works fine. I don't know what's the problem...

`
const multer = require("multer");
const config = { dest: "./uploads/" };

module.exports = items => (req, res, next) => {
  const upload = multer(config);
  const single = typeof items === "string";
  (single ? upload.single(items) : upload.fields(items))(req, res, err => {
    if (err instanceof multer.MulterError) {
      // A Multer error occurred when uploading.
    } else if (err) {
      // An unknown error occurred when uploading.
    }

    console.log("Uploader", err, req.file);

    // Everything went fine.
    next();
  });
};
`

and it produces: 
`
 Uploader MulterError: Unexpected field
    at wrappedFileFilter (/Users/yadirhb/workspace/mum/mwa/mwa-homework06-expressjs-02-yadirhb/node_modules/multer/index.js:40:19)
    at Busboy.<anonymous> (/Users/yadirhb/workspace/mum/mwa/mwa-homework06-expressjs-02-yadirhb/node_modules/multer/lib/make-middleware.js:114:7)
    at Busboy.emit (events.js:210:5)
    at Busboy.emit (/Users/yadirhb/workspace/mum/mwa/mwa-homework06-expressjs-02-yadirhb/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/Users/yadirhb/workspace/mum/mwa/mwa-homework06-expressjs-02-yadirhb/node_modules/busboy/lib/types/multipart.js:213:13)
    at PartStream.emit (events.js:210:5)
    at HeaderParser.<anonymous> (/Users/yadirhb/workspace/mum/mwa/mwa-homework06-expressjs-02-yadirhb/node_modules/dicer/lib/Dicer.js:51:16)
    at HeaderParser.emit (events.js:210:5)
    at HeaderParser._finish (/Users/yadirhb/workspace/mum/mwa/mwa-homework06-expressjs-02-yadirhb/node_modules/dicer/lib/HeaderParser.js:68:8)
    at SBMH.<anonymous> (/Users/yadirhb/workspace/mum/mwa/mwa-homework06-expressjs-02-yadirhb/node_modules/dicer/lib/HeaderParser.js:40:12) {
  name: 'MulterError',
  message: 'Unexpected field',
  code: 'LIMIT_UNEXPECTED_FILE',
  field: 'picture',
  storageErrors: []
}
`

**Comment by yadirhb** [comment]
Dummy error of mine...
