### ISSUE TITLE
TypeError: upload is not a function

### ISSUE THREAD

**Issue by vladciphersky** [expressjs/multer#886]
Hi. I tried to upload some file to skins folder, and i get error.
Full code:
```js
const multer = require("multer");
const upload = multer({
    dest: "skins/",
    limits: {
        fields: 1,
        fileSize: 64000,
        files: 1,
        parts: 1
    },
    fileFilter: (req, file, cb) => {
        if(!file.originalname.match(/\.(jpg|png)$/)) {
            return cb(new Error("Разрешена загрузка только PNG и JPG формата."));
        }
        cb(null, true);
    }
});

const express = require('express');
const router = express.Router();

router.get("/skin", (req, res) => {
    if(!req.cookies.loginHash) return res.redirect("/panel/login");
    account.promise().query("SELECT * FROM accounts WHERE lk_cookie = ?", [req.cookies.loginHash])
        .then((user) => {
            if(!user[0][0]) {
                res.cookie("loginHash", null, { maxAge: -1 });
                res.cookie("userLogin", null, { maxAge: -1 });
                return res.redirect("/panel/login");
            } else {
                if(req.query.error) return res.render("panel/skin", { error: errorProcess(req.query.error), userLogin: req.cookies.userLogin || "Личный кабинет" });
                else return res.render("panel/skin", { error: null, userLogin: req.cookies.userLogin || "Личный кабинет" });
            }
        }).catch(console.error);
});

router.post("/skin", upload.single("skin"), (req, res, next) => {
    account.promise().query("SELECT * FROM accounts WHERE lk_cookie = ?", [req.cookies.loginHash])
        .then((user) => {
            if(!user[0][0]) return res.redirect("/");
            else {
                upload(req, res, function (err) {
                    if (err instanceof multer.MulterError) {
                        console.error(err.stack); // multer
                        res.status(500).render("error", { error: 500, errorProcessed: "Ошибка Multer. Обратитесь в нашу группу ВКонтакте.", userLogin: req.cookies.userLogin || "Личный кабинет" });
                    } else {
                        console.error(err.stack); // not multer
                        res.status(500).render("error", { error: 500, errorProcessed: "Неизвестная ошибка. Обратитесь в нашу группу ВКонтакте.", userLogin: req.cookies.userLogin || "Личный кабинет" });
                    }
                
                    return res.redirect("/panel/event?type=SuccessSkinChange");
                });
            }
        }).catch(console.error);
});

router.listen(3000);
```

Error:
```bash
TypeError: upload is not a function
    at d:\Oxygen\CipherskyExtension\github\rangemc\rangemc.ovh\panel.js:100:17
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by vladciphersky** [comment]
Not actually.
