### ISSUE TITLE
Execution problems with res.locals middleware on my app when used with new Date().toISOString()

### ISSUE THREAD

**Issue by Necrolynn47** [expressjs/multer#888]
I am trying to save an image upload in my server through the filename attribute that the multer middleware provides me with. Coming across a really bizarre error.

Following how my instructor is going about his thing, I first saved the filename using the file.filename + '-' + file.original name syntax. Seems to work properly; haven't got the backend fired up yet, so I get redirected to a 500 statuscode page. The image too gets stored in the intended destination 'images' folder in my nodejs server.

`const fileStorage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, 'images');
  },
  filename: (req, file, cb) => {
    cb(null, file.filename + '-' + file.originalname);
  }
});`

Here's the relevant middleware for multer:

`app.use(multer({storage: fileStorage }).single('image'));`

Next, I tweak up the fileStroage method, and try his approach of saving in a date with screenshot style using the new Date().toISOString() method.

`const fileStorage = multer.diskStorage({
      destination: (req, file, cb) => {
        cb(null, 'images');
      },
      filename: (req, file, cb) => {
        cb(null, new Date().toISOString() + '-' + file.originalname);
      }
    });`

But instead of redirecting back to the backend error page, I get to this error with my app.

`TypeError: Cannot read property 'isLoggedIn' of undefined
    at C:\Users\Bhowal Soham\Desktop\NODE_Project\app.js:117:34
    at Layer.handle_error (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:315:13)
    at C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:284:7        
    at Function.process_params (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:275:10)    at Layer.handle_error (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:315:13)
    at C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:284:7        
    at Function.process_params (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:275:10)    at Layer.handle_error (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:315:13)
    at C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:284:7        
    at Function.process_params (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Bhowal Soham\Desktop\NODE_Project\node_modules\express\lib\router\index.js:275:10)`

isLoggedIn refers to one of the parameters I try setting locally with res.locals for each of my incoming requests. Chronologically. it is one of the first middleware to get executed in my app.

`app.use((req, res, next) => {
  res.locals.isAuthenticated = req.session.isLoggedIn;
  console.log(req.session.isLoggedIn);
  res.locals.csrfToken = req.csrfToken();
  if (!req.session.user) {
    return next();
  }
  res.locals.username = req.session.user.name;
  next();
});
`

Initially I guessed that the error had something to do with the fileFilter parameters I later tried to add to my multer middleware. The app works fine now (without the Date method), but it's really weird that I'm getting such a weird error with the Date().toISOString() method. I mean the request skips one of my universal middlewares, that's got to be one of the weirdest bugs I've tried to debug. Oh, and not to mention my instructor didn't seem to be having any such errors when he tried the date method in his video.

Any idea as to what might be going wrong? Might I be missing a 3rd party package or something? Because it'd be really convenient to get the storage by date option for my uploads.

**Comment by jonchurch** [comment]
It seems like the error occurs because `res.session` is undefined. 

Without seeing more of your code I can't say much more, or what might be causing the issue. 

**I'm not certain this is an issue with Multer, so I'm going to close until we get more information.** If you can post your project's repo to github, someone might be able to take a look for you.

One thing I will say is that it's not best practice to use multer as an app level middleware, where it will run for every single route in the app, i.e.:

```js
app.use(multer({storage: fileStorage }).single('image'));
```

It's best to use it with a specific route or set of routes that expect a file to be uploaded:

```js
const uploadImage = multer({storage: fileStorage }).single('image')

app.post('/upload', uploadImage, (req, res, next) => {})
```
