### ISSUE TITLE
multer.diskStorage() gets called tough fileSize reached

### ISSUE THREAD

**Issue by Mercury7639** [expressjs/multer#934]
```js
const express = require("express");
const router = express.Router();

const multer = require('multer')
const fs = require("fs");

function makeid(length) {
    var result = '';
    var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    var charactersLength = characters.length;
    for (var i = 0; i < length; i++) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
}

var storage = multer.diskStorage({
    destination: (req, file, cb) => {
        console.log(req.file);
        var ranID = makeid(10);

        fs.mkdirSync(`uploads/${ranID}`);
        var html = `<p>${file.originalname}</p><br><a href="./${file.originalname}" download>Download</a>`;
        fs.writeFileSync(`uploads/${ranID}/index.html`, html);

        cb(null, `uploads/${ranID}`)
    },
    filename: (req, file, cb) => cb(null, file.originalname)
})

var upload = multer({ storage: storage, limits: { files: 1, fileSize: 5 * (1024 ** 2) } }).single("file");

router.get("/", (req, res) => {
    res.json({
        status: "UPLOAD ROUTE WORKING!"
    })
})

router.post('/', function (req, res) {
    upload(req, res, (err) => {
        if (err) {
            res.end("File too large!");
            return console.log(err)
        } else {
            res.end(`https://deelixe.de:7777/${req.file.destination}`)
        }
    })
})



module.exports = router
```

The problem is that fs.mkdir creates the directory even tough the fileSize has reached and I cannot get the attribute .size cause the output of console.log(req.file); is 
```json
{
"fieldname": "file",
"originalname": "106 The Lincolnshire Poacher.mp3",
"encoding": "7bit",
"mimetype": "audio/mpeg"
}
``` 
So I can't get the file size to prevent fs from creating a directory with the index.html inside it

If I try to upload a file which is bigger than 5MB i see in the console
```log

1|api  | MulterError: File too large
1|api  |     at abortWithCode (/home/ubuntu/backend/node_modules/multer/lib/make-middleware.js:79:22)
1|api  |     at FileStream.<anonymous> (/home/ubuntu/backend/node_modules/multer/lib/make-middleware.js:141:11)
1|api  |     at FileStream.emit (events.js:315:20)
1|api  |     at PartStream.onData (/home/ubuntu/backend/node_modules/busboy/lib/types/multipart.js:220:18)
1|api  |     at PartStream.emit (events.js:315:20)
1|api  |     at addChunk (_stream_readable.js:295:12)
1|api  |     at readableAddChunk (_stream_readable.js:271:9)
1|api  |     at PartStream.Readable.push (_stream_readable.js:212:10)
1|api  |     at Dicer._oninfo (/home/ubuntu/backend/node_modules/dicer/lib/Dicer.js:191:36)
1|api  |     at SBMH.<anonymous> (/home/ubuntu/backend/node_modules/dicer/lib/Dicer.js:127:10) {
1|api  |   code: 'LIMIT_FILE_SIZE',
1|api  |   field: 'file',
1|api  |   storageErrors: []
1|api  | }
```
And the file isn't uploaded BUT there is an empty directory with the index.html

**Comment by davidmashe** [comment]
Not sure this counts as a multer error? Can you handle the exception and then dynamically (probably asycnhronously) delete any created directories in a `.catch()` block? If you want to open a PR with alternative error handling behavior, we can review it.

**Comment by Mercury7639** [comment]
No cause when it fails I can't get the path or even the file this is the problem
There is no way
