### ISSUE TITLE
multer error - unexpected field

### ISSUE THREAD

**Issue by bigalnz** [expressjs/multer#941]
I am trying to parse multi-part data with multer.

The incoming POST data looks like:

POST {
  host: '192.168.78.243:3000',
  accept: '*/*',
  'content-length': '1178',
  'content-type': 'multipart/form-data; boundary=------------------------f519f81dc2e1d562'
}
--------------------------f519f81dc2e1d562
Content-Disposition: form-data; name="event"; filename="event_3913.json"
Content-Type: application/octet-stream

{"packetCounter":"3913",
"capture_timestamp":"1600677267347",
"datetime":"20200921 204027000",
"stateUTF8":"ABC123",
"stateASCII":"ABC123",
.....

My simple setup is:

var express = require('express')
var multer  = require('multer')
var upload = multer()
var app = express()

app.post('/', (req, res) => {
    console.log('hello');
    res.send(200);
});

app.listen(3000, () => { console.log('server running')});

When a request comes in the error is : 

al@al-ubuntu20lts-vm:~/test$ node index.js
server running
MulterError: Unexpected field
    at wrappedFileFilter (/home/al/test/node_modules/multer/index.js:40:19)
    at Busboy.<anonymous> (/home/al/test/node_modules/multer/lib/make-middleware.js:114:7)
    at Busboy.emit (events.js:198:13)
    at Busboy.emit (/home/al/test/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/home/al/test/node_modules/busboy/lib/types/multipart.js:213:13)
    at PartStream.emit (events.js:198:13)
    at HeaderParser.<anonymous> (/home/al/test/node_modules/dicer/lib/Dicer.js:51:16)
    at HeaderParser.emit (events.js:198:13)
    at HeaderParser._finish (/home/al/test/node_modules/dicer/lib/HeaderParser.js:68:8)
    at SBMH.<anonymous> (/home/al/test/node_modules/dicer/lib/HeaderParser.js:40:12)
MulterError: Unexpected field
    at wrappedFileFilter (/home/al/test/node_modules/multer/index.js:40:19)
    at Busboy.<anonymous> (/home/al/test/node_modules/multer/lib/make-middleware.js:114:7)
    at Busboy.emit (events.js:198:13)
    at Busboy.emit (/home/al/test/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/home/al/test/node_modules/busboy/lib/types/multipart.js:213:13)
    at PartStream.emit (events.js:198:13)
    at HeaderParser.<anonymous> (/home/al/test/node_modules/dicer/lib/Dicer.js:51:16)
    at HeaderParser.emit (events.js:198:13)
    at HeaderParser._finish (/home/al/test/node_modules/dicer/lib/HeaderParser.js:68:8)
    at SBMH.<anonymous> (/home/al/test/node_modules/dicer/lib/HeaderParser.js:40:12)
^C

**Comment by shreyasg-git** [comment]
hey @bigalnz  I don't think you have provided all the necessary code that deals with multer in here...still by reading your error message I think the `name` field in your form-data while POSTing it must be same as `fieldName` in upload.single(`fieldName`).
